[hebTalmudBavli_Chagigah]
DataPath=./modules/genbook/rawgenbook/hebTalmudBavli_Chagigah/hebTalmudBavli_Chagigah
ModDrv=RawGenBook
BlockType=CHAPTER
SourceType=OSIS
CompressType=ZIP
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISLemma
GlobalOptionFilter=OSISStrongs
GlobalOptionFilter=OSISMorph
GlobalOptionFilter=UTF8HebrewPoints
Encoding=UTF-8
Lang=hbo
Feature=NoParagraphs
Feature=StrongsNumbers
Version=1.0
VersionDate=2026-07-04
History_1.0=Erstversion – Sefaria William Davidson Edition - Aramaic
Description=Talmud Bavli Hebräisch – Chagiga (חֲגִיגָה) – Seder Moed
About=Talmud Bavli – hebräisch/aramäischer Originaltext (mit Niqqud). Jedes hebräische/aramäische Wort ist mit einer Strong-Nummer (H-Nummer) versehen (automatisch per Wörterbuch/spaCy). \par Quelle: Sefaria – www.sefaria.org \par Version: William Davidson Edition - Aramaic \par Lizenz: Public Domain \par Traktat: Chagiga (חֲגִיגָה) \par Seder: Seder Moed (סֵדֶר מוֹעֵד)
DistributionLicense=Public Domain
DistributionSource=https://www.sefaria.org/texts/Talmud
TextSource=https://www.sefaria.org/texts/Talmud
cover=cover.png
