[deuPfleidererGrafiken]
DataPath=./modules/genbook/rawgenbook/deuPfleidererGrafiken/deuPfleidererGrafiken
ModDrv=RawGenBook
BlockType=CHAPTER
SourceType=OSIS
Category=Images
CompressType=ZIP
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISScripref
GlobalOptionFilter=OSISHeadings
Encoding=UTF-8
Lang=de
LCSH=Bible--Images.
Description=Bilder & Grafiken von Daniel Pfleiderer - https://crossload.org
About= CC BY-NC  \par https://crossload.org/autoren/daniel-pfleiderer
Version=1.0
History_1.0=Initial version
MinimumVersion=1.6.1
DistributionLicense=(CC BY-NC ) Creative Commons Namensnennung 4.0 International
CopyrightHolder=Daniel Pfleiderer (CC BY-NC )
