[deuEvangeliumsLieder]
DataPath=./modules/comments/rawcom/deuEvangeliumsLieder/
ModDrv=RawCom
SourceType=OSIS
Encoding=UTF-8
BlockType=BOOK
Versification=Luther
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISHeadings
Lang=de
Version=1.0
MinimumVersion=1.5.1a
Description=Evangeliums-Lieder nach Bibelstellen
About=Sammlung christlicher Lieder geordnet nach Bibelstellen. \par\par Quelle: https://www.evangeliums.net/lieder/bibelstellen.php \par\par Bitte beachten Sie das Urheberrecht der einzelnen Liedtexte.
DistributionSource=https://www.evangeliums.net/lieder/bibelstellen.php
TextSource=https://www.evangeliums.net/lieder/bibelstellen.php
Keywords=songs hymns Lieder Kirchenlieder
