[deuKindergottesdienst]
DataPath=./modules/comments/rawcom/deuKindergottesdienst/
ModDrv=RawCom
SourceType=OSIS
Encoding=UTF-8
BlockType=BOOK
Versification=Luther
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISHeadings
Lang=de
Description=Kindergottesdienst - Biblische Geschichten für Kinder
About=Bibelgeschichten und Stundenentwürfe für Kindergottesdienst und Kinderkirche (www.derKindergottesdienst.de)
Version=1.0
MinimumVersion=1.5.1a
Keywords=Kindergottesdienst Kinderkirche Kinder Geschichten children church stories
LCSH=Bible stories, German
