[hebMishnah]
DataPath=./modules/genbook/rawgenbook/hebMishnah/hebMishnah
ModDrv=RawGenBook
BlockType=CHAPTER
SourceType=OSIS
CompressType=ZIP
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISLemma
GlobalOptionFilter=OSISStrongs
GlobalOptionFilter=OSISMorph
GlobalOptionFilter=UTF8HebrewPoints
Encoding=UTF-8
Lang=hbo
Feature=NoParagraphs
Feature=StrongsNumbers
Version=1.0
VersionDate=2026-07-01
History_1.0=Erstversion – Sefaria Torat Emet 357
Description=Mischna – Hebräisch (Torat Emet 357) – alle 6 Seder
About=Hebräischer Mischna-Text (Torat Emet 357, mit Niqqud) – alle 6 Seder und 63 Traktate. Jedes Wort ist mit einer Strong-Nummer (H-Nummer) und einer OSHM-Morphologie versehen (automatisch per spaCy / Wörterbuch). \par Quelle: Sefaria – www.sefaria.org \par Version: Torat Emet 357 \par Originalquelle: www.toratemetfreeware.com \par Lizenz: Public Domain
DistributionLicense=Public Domain
DistributionSource=http://www.toratemetfreeware.com/index.html?downloads
TextSource=http://www.toratemetfreeware.com/index.html?downloads
cover=cover.png
