[hebMekhilta]
DataPath=./modules/genbook/rawgenbook/hebMekhilta/hebMekhilta
ModDrv=RawGenBook
BlockType=CHAPTER
SourceType=OSIS
CompressType=ZIP
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISLemma
GlobalOptionFilter=OSISStrongs
GlobalOptionFilter=OSISMorph
GlobalOptionFilter=UTF8HebrewPoints
Encoding=UTF-8
Lang=hbo
Feature=NoParagraphs
Feature=StrongsNumbers
Version=1.0
VersionDate=2026-07-04
History_1.0=Erstversion – Sefaria
Description=Mekhilta DeRabbi Yishmael – Hebräisch
About=Mekhilta DeRabbi Yishmael – Tannaitischer Midrasch zu Exodus (hebräisch). \par Quelle: Sefaria – www.sefaria.org \par Lizenz: Public Domain
DistributionLicense=Public Domain
DistributionSource=https://www.sefaria.org/texts/Midrash
TextSource=https://www.sefaria.org/texts/Midrash
cover=cover.png
