[deuEvangeliumsSermon]
Abbreviation=deuEvangeliumsSermon
DataPath=./modules/comments/zcom/deuEvangeliumsSermon
ModDrv=RawCom
SourceType=OSIS
Encoding=UTF-8
BlockType=BOOK
Versification=Luther
SwordVersionDate=2026-05-08
LCSH=Bible N.T.--Sermon.
Lang=de
Description=Andachten und Predigten - Evangeliums.net - Das Online-Portal für Christen
About=10.798 biblische Andachten und Predigten - Evangeliums.net
Version=1.0
History_1.0=Initial version
MinimumVersion=1.6.1
DistributionLicense=(CC BY 4.0) Creative Commons Namensnennung 4.0 International/ Gemeinfrei
