[deuStrehleHymns]
DataPath=./modules/comments/rawcom/deuStrehleHymns/
ModDrv=RawCom
SourceType=OSIS
Encoding=UTF-8
BlockType=BOOK
Versification=Luther
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISHeadings
Lang=de
Version=1.0
MinimumVersion=1.5.1a
Description=Liederdatenbank nach Bibelstellen (Strehle)
About=Lieder geordnet nach Bibelstellen. Quelle: https://liederdatenbank.strehle.de/bible \par\par Die Liederdatenbank von Thomas Strehle ist eine umfangreiche Sammlung christlicher Lieder mit Angaben zu Autoren, Liederbüchern und thematischen Stichwörtern.
DistributionSource=https://liederdatenbank.strehle.de/bible
TextSource=https://liederdatenbank.strehle.de/bible
Keywords=songs hymns Lieder Kirchenlieder
